title: "Georgios Peikos"
description: "Applied AI Engineer and Search/NLP Researcher specializing in LLMs, Retrieval Augmented Generation, Information Retrieval, and trustworthy AI systems."
url: "https://giorgospeikos.github.io"
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
collections:
  projects:
    output: true
    permalink: /projects/:name/
